# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: interface/package-lock.json
    - name: "NPM CI"
      run: npm ci
      working-directory: ./interface
    - name: "NPM BUILD"
      run: npm run build --if-present
      working-directory: ./interface
    - name: "RENAME BUILD FOLDER"
      run: cp interface/build interface/github-build
    - uses: actions-go/push@v1
      with:
        commit-files: interface/build
